// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wxjtpzjjrpgirylpnmuw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind4anRwempqcnBnaXJ5bHBubXV3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4OTA2OTksImV4cCI6MjA1ODQ2NjY5OX0.37-1WH1sp0LSXnh7FVMQPPU-aQz9RyWQXgAq6EhmEW8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);